import { getCollection } from "astro:content";
import type {
  SidebarEntry,
  SidebarGroup,
  SidebarLink,
} from "@astrojs/starlight/utils/routing/types";
import { inferGroupDirectory, reorderGroupEntries } from "./meta-ordering";

type FrontmatterMap = Map<string, { title: string }>;

let cachedMap: FrontmatterMap | null = null;

/**
 * Build a map from href (e.g. "/engineering/architecture/") to frontmatter.
 * Memoized at module level so it's only built once per build/dev session.
 */
export async function buildFrontmatterMap(): Promise<FrontmatterMap> {
  if (cachedMap) return cachedMap;

  const docs = await getCollection("docs");
  const map: FrontmatterMap = new Map();

  for (const entry of docs) {
    // entry.id is like "engineering/architecture" or "engineering/architecture/data-access-patterns"
    // The corresponding href is "/" + id + "/"
    const href = "/" + entry.id + "/";
    map.set(href, { title: entry.data.title });
  }

  cachedMap = map;
  return map;
}

/**
 * Recursively process sidebar entries:
 * 1. Override group labels with frontmatter title from index pages
 * 2. Flatten single-child groups (group with 1 link child -> just the link)
 * 3. Convert remaining kebab-case group labels to Title Case
 */
export function processSidebar(
  entries: SidebarEntry[],
  map: FrontmatterMap,
): SidebarEntry[] {
  return entries.map((entry) => processEntry(entry, map)).filter(Boolean) as SidebarEntry[];
}

function processEntry(
  entry: SidebarEntry,
  map: FrontmatterMap,
): SidebarEntry {
  if (entry.type === "link") {
    return entry;
  }

  // It's a group -- recurse into children first
  const group = entry as SidebarGroup;
  const processedChildren = processSidebar(group.entries, map);

  // Reorder children if the directory has a _meta.ts ordering
  const dirPath = inferGroupDirectory(group);
  const orderedChildren = dirPath
    ? reorderGroupEntries(processedChildren, dirPath)
    : processedChildren;

  // Try to find an index page link in this group to get a better label
  const betterLabel = findGroupTitle(orderedChildren, map);

  // Determine final label: frontmatter title > kebab-to-title > original
  const finalLabel = betterLabel || prettifyLabel(group.label);

  // Flatten: if group has exactly 1 child that is a link, replace group with that link
  if (orderedChildren.length === 1 && orderedChildren[0]!.type === "link") {
    const onlyChild = orderedChildren[0] as SidebarLink;
    return {
      ...onlyChild,
      label: finalLabel,
    };
  }

  return {
    ...group,
    label: finalLabel,
    entries: orderedChildren,
  };
}

/**
 * Look for an index page among a group's children and return its frontmatter title.
 */
function findGroupTitle(
  children: SidebarEntry[],
  map: FrontmatterMap,
): string | null {
  // Strategy 1: find a link that is a prefix of other links (index page pattern)
  const links = children.filter((c): c is SidebarLink => c.type === "link");

  for (const link of links) {
    const fm = map.get(link.href);
    if (fm?.title) {
      const isIndex = children.some(
        (other) =>
          other !== link &&
          ((other.type === "link" && other.href.startsWith(link.href)) ||
            (other.type === "group" && hasLinksUnder(other, link.href))),
      );
      if (isIndex) {
        return fm.title;
      }
    }
  }

  // Strategy 2: find the shortest href link if others are nested under it
  if (links.length > 0) {
    const sorted = [...links].sort((a, b) => a.href.length - b.href.length);
    const shortest = sorted[0]!;
    const othersNested =
      links.some((l) => l !== shortest && l.href.startsWith(shortest.href)) ||
      children.some(
        (c) => c.type === "group" && hasLinksUnder(c, shortest.href),
      );
    if (othersNested) {
      const fm = map.get(shortest.href);
      if (fm?.title) return fm.title;
    }
  }

  return null;
}

/** Check if a group (recursively) contains any link whose href starts with the given prefix. */
function hasLinksUnder(group: SidebarGroup, prefix: string): boolean {
  return group.entries.some((entry) => {
    if (entry.type === "link") return entry.href.startsWith(prefix);
    return hasLinksUnder(entry, prefix);
  });
}

/**
 * Convert a raw directory-derived label to a readable title.
 * Handles kebab-case ("invoice-factoring" -> "Invoice Factoring") and
 * single lowercase words ("payments" -> "Payments").
 * Preserves labels that already contain uppercase (manually configured labels).
 */
function prettifyLabel(label: string): string {
  // Skip if the label already has any uppercase (it was manually set, not autogenerated)
  if (label !== label.toLowerCase()) {
    return label;
  }

  // Known acronyms/abbreviations to keep uppercase
  const acronyms = new Set([
    "ai", "api", "apis", "aws", "bff", "c2d", "cdp", "ci", "cli",
    "css", "db", "e2e", "erm", "iam", "kyb", "kyc", "mcp", "mfa",
    "ml", "nft", "rpc", "sdk", "sms", "ui", "ux", "usdc",
  ]);

  return label
    .split("-")
    .map((word) => {
      if (acronyms.has(word)) return word.toUpperCase();
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(" ");
}
